version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: aiforus_mysql_prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-aiforusdb}
      MYSQL_USER: ${MYSQL_USER:-aiforus}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-pass1234}
    ports:
      - "127.0.0.1:3306:3306"  # 只绑定到本地，增强安全性
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aiforus_network
    command: --default-authentication-plugin=mysql_native_password

  # 后端应用
  backend:
    image: maozain/aiforus-backend:latest  # 请修改为您的镜像名
    container_name: aiforus_backend_prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_USER: ${MYSQL_USER:-aiforus}
      DB_PASSWORD: ${MYSQL_PASSWORD:-pass1234}
      DB_NAME: ${MYSQL_DATABASE:-aiforusdb}
      JWT_SECRET: ${JWT_SECRET:-d7f3a1e9b5c42f8e92c5d1477b3e0a6f9b48c1d7a5e62f3b8c1d4f0a9e7b2c3d}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    volumes:
      - backend_logs:/app/logs
    networks:
      - aiforus_network

  # 前端应用
  frontend:
    image: maozain/aiforus-frontend:latest  # 请修改为您的镜像名
    container_name: aiforus_frontend_prod
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - aiforus_network

volumes:
  mysql_data:
    driver: local
  backend_logs:
    driver: local

networks:
  aiforus_network:
    driver: bridge
